In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./../data/acs_5yr_merged_v3.csv')

In [3]:
df

,zip,do_date,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,...,some_college_and_associates_degree,walked_to_work,worked_at_home,workers_16_and_over,commute_35_44_mins,commute_60_more_mins,commute_less_10_mins,commuters_16_over,hispanic_any_race,year
0,1013,20072011,3553,5549,1949.0,217.0,914.0,513.0,517.0,519.0,...,3798.0,284.0,96.0,9574.0,292.0,281.0,1396.0,9478.0,4899,2011
1,1013,20082012,3688,5217,1950.0,251.0,931.0,496.0,448.0,500.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046,2012
2,1013,20092013,3713,5297,1947.0,241.0,925.0,590.0,371.0,699.0,...,3441.0,361.0,142.0,9597.0,393.0,370.0,1586.0,9455.0,4820,2013
3,1013,20102014,3615,5516,1942.0,189.0,955.0,502.0,277.0,824.0,...,3828.0,353.0,154.0,9826.0,416.0,362.0,1679.0,9672.0,5296,2014
4,1013,20112015,3784,5412,1942.0,194.0,1013.0,599.0,257.0,737.0,...,3893.0,265.0,233.0,10008.0,442.0,274.0,1732.0,9775.0,5411,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92647,99901,20092013,1952,3343,1975.0,152.0,409.0,175.0,79.0,194.0,...,3215.0,860.0,156.0,6809.0,96.0,63.0,2436.0,6653.0,601,2013
92648,99901,20102014,2094,3211,1976.0,183.0,455.0,205.0,116.0,220.0,...,3211.0,770.0,164.0,6690.0,95.0,73.0,2423.0,6526.0,636,2014
92649,99901,20112015,2010,3257,1975.0,134.0,387.0,232.0,117.0,198.0,...,3288.0,713.0,167.0,6637.0,44.0,63.0,2379.0,6470.0,663,2015
92650,99901,20122016,1919,3290,1976.0,132.0,421.0,192.0,163.0,158.0,...,3448.0,629.0,197.0,6804.0,61.0,82.0,2397.0,6607.0,634,2016
92651,99901,20132017,1860,3410,1976.0,119.0,439.0,195.0,193.0,172.0,...,3569.0,569.0,182.0,6804.0,81.0,89.0,2402.0,6622.0,655,2017

In [4]:
df['zip'] = df['zip'].map(lambda x: str(x))

In [5]:
df['zip'] = df['zip'].map(lambda x: '0'+x if len(x) < 5 else x)

In [7]:
df['zip'].map(lambda x: len(x)).value_counts()

5    92652
Name: zip, dtype: int64

In [8]:
df

,zip,do_date,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,...,some_college_and_associates_degree,walked_to_work,worked_at_home,workers_16_and_over,commute_35_44_mins,commute_60_more_mins,commute_less_10_mins,commuters_16_over,hispanic_any_race,year
0,01013,20072011,3553,5549,1949.0,217.0,914.0,513.0,517.0,519.0,...,3798.0,284.0,96.0,9574.0,292.0,281.0,1396.0,9478.0,4899,2011
1,01013,20082012,3688,5217,1950.0,251.0,931.0,496.0,448.0,500.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046,2012
2,01013,20092013,3713,5297,1947.0,241.0,925.0,590.0,371.0,699.0,...,3441.0,361.0,142.0,9597.0,393.0,370.0,1586.0,9455.0,4820,2013
3,01013,20102014,3615,5516,1942.0,189.0,955.0,502.0,277.0,824.0,...,3828.0,353.0,154.0,9826.0,416.0,362.0,1679.0,9672.0,5296,2014
4,01013,20112015,3784,5412,1942.0,194.0,1013.0,599.0,257.0,737.0,...,3893.0,265.0,233.0,10008.0,442.0,274.0,1732.0,9775.0,5411,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92647,99901,20092013,1952,3343,1975.0,152.0,409.0,175.0,79.0,194.0,...,3215.0,860.0,156.0,6809.0,96.0,63.0,2436.0,6653.0,601,2013
92648,99901,20102014,2094,3211,1976.0,183.0,455.0,205.0,116.0,220.0,...,3211.0,770.0,164.0,6690.0,95.0,73.0,2423.0,6526.0,636,2014
92649,99901,20112015,2010,3257,1975.0,134.0,387.0,232.0,117.0,198.0,...,3288.0,713.0,167.0,6637.0,44.0,63.0,2379.0,6470.0,663,2015
92650,99901,20122016,1919,3290,1976.0,132.0,421.0,192.0,163.0,158.0,...,3448.0,629.0,197.0,6804.0,61.0,82.0,2397.0,6607.0,634,2016
92651,99901,20132017,1860,3410,1976.0,119.0,439.0,195.0,193.0,172.0,...,3569.0,569.0,182.0,6804.0,81.0,89.0,2402.0,6622.0,655,2017

In [10]:
df.rename(columns = {'year':'year_usable'}, inplace = True)

In [39]:
df['year_usable'][0]

numpy.int64

In [12]:
df['year_usable'] = df['year_usable'] + 2

In [27]:
(df['poverty']/df['total_pop'])

0        0.185655
1        0.196270
2        0.168724
3        0.151262
4        0.164955
           ...
92647    0.099846
92648    0.112458
92649    0.119560
92650    0.106511
92651    0.105317
Length: 92652, dtype: float64

In [28]:
(df['poverty']/df['pop_determined_poverty_status'])

0.257831020790369

In [26]:
df['pop_determined_poverty_status']

0        21819.0
1        21251.0
2        21493.0
3        21664.0
4        21753.0
          ...
92647    13383.0
92648    13456.0
92649    13532.0
92650    13540.0
92651    13553.0
Name: pop_determined_poverty_status, Length: 92652, dtype: float64

In [ ]:
# engineer average commute length
# mode of commute
# income per capita
# poverty rate

In [30]:
zri = pd.read_csv('./../data/zri_multifamily_v2.csv')

In [31]:
zri

,zip,City,State,Metro,CountyName,year-month,zri
0,1013,Chicopee,MA,Springfield,Hampden County,2014-02,931.0
1,1013,Chicopee,MA,Springfield,Hampden County,2014-03,934.0
2,1013,Chicopee,MA,Springfield,Hampden County,2014-04,929.0
3,1013,Chicopee,MA,Springfield,Hampden County,2014-05,929.0
4,1013,Chicopee,MA,Springfield,Hampden County,2014-06,929.0
...,...,...,...,...,...,...,...
92437,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-08,1277.0
92438,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-09,1271.0
92439,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-10,1299.0
92440,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-11,1261.5
92441,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-12,1224.0

In [42]:
zri['zip'] = zri['zip'].map(lambda x: str(x))

In [43]:
zri['zip'] = zri['zip'].map(lambda x: '0'+x if len(x)<5 else x)

In [45]:
zri['zip'].map(lambda x: len(x)).value_counts()

5    92442
Name: zip, dtype: int64

In [35]:
zri['year'] = zri['year-month'].map(lambda x: int(x[0:4]))

In [46]:
merged = pd.merge(zri, df, left_on = ['zip', 'year'], right_on = ['zip', 'year_usable'], how = 'left')

In [48]:
merged = merged.sort_values(['zip', 'year-month'])

In [49]:
merged

,zip,City,State,Metro,CountyName,year-month,zri,year,do_date,nonfamily_households,...,some_college_and_associates_degree,walked_to_work,worked_at_home,workers_16_and_over,commute_35_44_mins,commute_60_more_mins,commute_less_10_mins,commuters_16_over,hispanic_any_race,year_usable
0,01013,Chicopee,MA,Springfield,Hampden County,2014-02,931.0,2014,20082012.0,3688.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046.0,2014.0
1,01013,Chicopee,MA,Springfield,Hampden County,2014-03,934.0,2014,20082012.0,3688.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046.0,2014.0
2,01013,Chicopee,MA,Springfield,Hampden County,2014-04,929.0,2014,20082012.0,3688.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046.0,2014.0
3,01013,Chicopee,MA,Springfield,Hampden County,2014-05,929.0,2014,20082012.0,3688.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046.0,2014.0
4,01013,Chicopee,MA,Springfield,Hampden County,2014-06,929.0,2014,20082012.0,3688.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046.0,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92437,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-08,1277.0,2019,20132017.0,5160.0,...,15324.0,434.0,1416.0,24847.0,795.0,5480.0,2822.0,23431.0,3067.0,2019.0
92438,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-09,1271.0,2019,20132017.0,5160.0,...,15324.0,434.0,1416.0,24847.0,795.0,5480.0,2822.0,23431.0,3067.0,2019.0
92439,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-10,1299.0,2019,20132017.0,5160.0,...,15324.0,434.0,1416.0,24847.0,795.0,5480.0,2822.0,23431.0,3067.0,2019.0
92440,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-11,1261.5,2019,20132017.0,5160.0,...,15324.0,434.0,1416.0,24847.0,795.0,5480.0,2822.0,23431.0,3067.0,2019.0
92441,99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,2019-12,1224.0,2019,20132017.0,5160.0,...,15324.0,434.0,1416.0,24847.0,795.0,5480.0,2822.0,23431.0,3067.0,2019.0

In [ ]:
merged.to_csv()