In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('./../data/acs_5yr_merged_v3.csv')

In [3]:
df

,zip,do_date,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,...,some_college_and_associates_degree,walked_to_work,worked_at_home,workers_16_and_over,commute_35_44_mins,commute_60_more_mins,commute_less_10_mins,commuters_16_over,hispanic_any_race,year
0,1013,20072011,3553,5549,1949.0,217.0,914.0,513.0,517.0,519.0,...,3798.0,284.0,96.0,9574.0,292.0,281.0,1396.0,9478.0,4899,2011
1,1013,20082012,3688,5217,1950.0,251.0,931.0,496.0,448.0,500.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046,2012
2,1013,20092013,3713,5297,1947.0,241.0,925.0,590.0,371.0,699.0,...,3441.0,361.0,142.0,9597.0,393.0,370.0,1586.0,9455.0,4820,2013
3,1013,20102014,3615,5516,1942.0,189.0,955.0,502.0,277.0,824.0,...,3828.0,353.0,154.0,9826.0,416.0,362.0,1679.0,9672.0,5296,2014
4,1013,20112015,3784,5412,1942.0,194.0,1013.0,599.0,257.0,737.0,...,3893.0,265.0,233.0,10008.0,442.0,274.0,1732.0,9775.0,5411,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92647,99901,20092013,1952,3343,1975.0,152.0,409.0,175.0,79.0,194.0,...,3215.0,860.0,156.0,6809.0,96.0,63.0,2436.0,6653.0,601,2013
92648,99901,20102014,2094,3211,1976.0,183.0,455.0,205.0,116.0,220.0,...,3211.0,770.0,164.0,6690.0,95.0,73.0,2423.0,6526.0,636,2014
92649,99901,20112015,2010,3257,1975.0,134.0,387.0,232.0,117.0,198.0,...,3288.0,713.0,167.0,6637.0,44.0,63.0,2379.0,6470.0,663,2015
92650,99901,20122016,1919,3290,1976.0,132.0,421.0,192.0,163.0,158.0,...,3448.0,629.0,197.0,6804.0,61.0,82.0,2397.0,6607.0,634,2016
92651,99901,20132017,1860,3410,1976.0,119.0,439.0,195.0,193.0,172.0,...,3569.0,569.0,182.0,6804.0,81.0,89.0,2402.0,6622.0,655,2017

In [4]:
df['zip'] = df['zip'].map(lambda x: str(x))

In [5]:
df['zip'] = df['zip'].map(lambda x: '0'+x if len(x) < 5 else x)

In [6]:
df['zip'].map(lambda x: len(x)).value_counts()

5    92652
Name: zip, dtype: int64

In [7]:
df

,zip,do_date,nonfamily_households,family_households,median_year_structure_built,rent_burden_not_computed,rent_over_50_percent,rent_40_to_50_percent,rent_35_to_40_percent,rent_30_to_35_percent,...,some_college_and_associates_degree,walked_to_work,worked_at_home,workers_16_and_over,commute_35_44_mins,commute_60_more_mins,commute_less_10_mins,commuters_16_over,hispanic_any_race,year
0,01013,20072011,3553,5549,1949.0,217.0,914.0,513.0,517.0,519.0,...,3798.0,284.0,96.0,9574.0,292.0,281.0,1396.0,9478.0,4899,2011
1,01013,20082012,3688,5217,1950.0,251.0,931.0,496.0,448.0,500.0,...,3697.0,280.0,159.0,9514.0,322.0,359.0,1506.0,9355.0,5046,2012
2,01013,20092013,3713,5297,1947.0,241.0,925.0,590.0,371.0,699.0,...,3441.0,361.0,142.0,9597.0,393.0,370.0,1586.0,9455.0,4820,2013
3,01013,20102014,3615,5516,1942.0,189.0,955.0,502.0,277.0,824.0,...,3828.0,353.0,154.0,9826.0,416.0,362.0,1679.0,9672.0,5296,2014
4,01013,20112015,3784,5412,1942.0,194.0,1013.0,599.0,257.0,737.0,...,3893.0,265.0,233.0,10008.0,442.0,274.0,1732.0,9775.0,5411,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92647,99901,20092013,1952,3343,1975.0,152.0,409.0,175.0,79.0,194.0,...,3215.0,860.0,156.0,6809.0,96.0,63.0,2436.0,6653.0,601,2013
92648,99901,20102014,2094,3211,1976.0,183.0,455.0,205.0,116.0,220.0,...,3211.0,770.0,164.0,6690.0,95.0,73.0,2423.0,6526.0,636,2014
92649,99901,20112015,2010,3257,1975.0,134.0,387.0,232.0,117.0,198.0,...,3288.0,713.0,167.0,6637.0,44.0,63.0,2379.0,6470.0,663,2015
92650,99901,20122016,1919,3290,1976.0,132.0,421.0,192.0,163.0,158.0,...,3448.0,629.0,197.0,6804.0,61.0,82.0,2397.0,6607.0,634,2016
92651,99901,20132017,1860,3410,1976.0,119.0,439.0,195.0,193.0,172.0,...,3569.0,569.0,182.0,6804.0,81.0,89.0,2402.0,6622.0,655,2017

In [8]:
df.rename(columns = {'year':'year_usable'}, inplace = True)

In [9]:
df['year_usable'][0]

2011

In [10]:
df['year_usable'] = df['year_usable'] + 2

In [11]:
# ——
# average commute time
# education: 
# education per income?
# -
# median year structure built
# average units per building
# —
# race: white black asian hispanic indian,… populations
# ———
# vacant housing units for rent (as a percentage?)
# age: pre-working age, millenial, working age, senior
# education: high-school, bachelor, advanced (as all perentages of pop)
# gini_index

In [12]:
list(df.columns)

['zip',
 'do_date',
 'nonfamily_households',
 'family_households',
 'median_year_structure_built',
 'rent_burden_not_computed',
 'rent_over_50_percent',
 'rent_40_to_50_percent',
 'rent_35_to_40_percent',
 'rent_30_to_35_percent',
 'rent_25_to_30_percent',
 'rent_20_to_25_percent',
 'rent_15_to_20_percent',
 'rent_10_to_15_percent',
 'rent_under_10_percent',
 'total_pop',
 'male_pop',
 'female_pop',
 'median_age',
 'white_pop',
 'black_pop',
 'asian_pop',
 'hispanic_pop',
 'amerindian_pop',
 'other_race_pop',
 'two_or_more_races_pop',
 'not_hispanic_pop',
 'commuters_by_public_transportation',
 'households',
 'income_per_capita',
 'housing_units',
 'vacant_housing_units',
 'vacant_housing_units_for_rent',
 'vacant_housing_units_for_sale',
 'owner_occupied_housing_units',
 'million_dollar_housing_units',
 'mortgaged_housing_units',
 'families_with_young_children',
 'two_parent_families_with_young_children',
 'two_parents_in_labor_force_families_with_young_children',
 'two_parents_father_in_labor_force_families_with_young_children',
 'two_parents_mother_in_labor_force_families_with_young_children',
 'two_parents_not_in_labor_force_families_with_young_children',
 'one_parent_families_with_young_children',
 'father_one_parent_families_with_young_children',
 'father_in_labor_force_one_parent_families_with_young_children',
 'commute_10_14_mins',
 'commute_15_19_mins',
 'commute_20_24_mins',
 'commute_25_29_mins',
 'commute_30_34_mins',
 'commute_45_59_mins',
 'income_less_10000',
 'income_10000_14999',
 'income_15000_19999',
 'income_20000_24999',
 'income_25000_29999',
 'income_30000_34999',
 'income_35000_39999',
 'income_40000_44999',
 'income_45000_49999',
 'income_50000_59999',
 'income_60000_74999',
 'income_75000_99999',
 'income_100000_124999',
 'income_125000_149999',
 'income_150000_199999',
 'income_200000_or_more',
 'owner_occupied_housing_units_median_value',
 'married_households',
 'occupied_housing_units',
 'housing_units_renter_occupied',
 'dwellings_1_units_detached',
 'dwellings_1_units_attached',
 'dwellings_2_units',
 'dwellings_3_to_4_units',
 'dwellings_5_to_9_units',
 'dwellings_10_to_19_units',
 'dwellings_20_to_49_units',
 'dwellings_50_or_more_units',
 'mobile_homes',
 'housing_built_2005_or_later',
 'housing_built_2000_to_2004',
 'housing_built_1939_or_earlier',
 'male_under_5',
 'male_5_to_9',
 'male_10_to_14',
 'male_15_to_17',
 'male_18_to_19',
 'male_20',
 'male_21',
 'male_22_to_24',
 'male_25_to_29',
 'male_30_to_34',
 'male_35_to_39',
 'male_40_to_44',
 'male_45_to_49',
 'male_50_to_54',
 'male_55_to_59',
 'male_60_61',
 'male_62_64',
 'male_65_to_66',
 'male_67_to_69',
 'male_70_to_74',
 'male_75_to_79',
 'male_80_to_84',
 'male_85_and_over',
 'female_under_5',
 'female_5_to_9',
 'female_10_to_14',
 'female_15_to_17',
 'female_18_to_19',
 'female_20',
 'female_21',
 'female_22_to_24',
 'female_25_to_29',
 'female_30_to_34',
 'female_35_to_39',
 'female_40_to_44',
 'female_45_to_49',
 'female_50_to_54',
 'female_55_to_59',
 'female_60_to_61',
 'female_62_to_64',
 'female_65_to_66',
 'female_67_to_69',
 'female_70_to_74',
 'female_75_to_79',
 'female_80_to_84',
 'female_85_and_over',
 'white_including_hispanic',
 'black_including_hispanic',
 'amerindian_including_hispanic',
 'asian_including_hispanic',
 'commute_5_9_mins',
 'commute_35_39_mins',
 'commute_40_44_mins',
 'commute_60_89_mins',
 'commute_90_more_mins',
 'households_retirement_income',
 'armed_forces',
 'civilian_labor_force',
 'employed_pop',
 'unemployed_pop',
 'not_in_labor_force',
 'pop_16_over',
 'pop_in_labor_force',
 'asian_male_45_54',
 'asian_male_55_64',
 'black_male_45_54',
 'black_male_55_64',
 'hispanic_male_45_54',
 'hispanic_male_55_64',
 'white_male_45_54',
 'white_male_55_64',
 'bachelors_degree_2',
 'bachelors_degree_or_higher_25_64',
 'children',
 'children_in_single_female_hh',
 'commuters_by_bus',
 'commuters_by_car_truck_van',
 'commuters_by_carpool',
 'commuters_by_subway_or_elevated',
 'commuters_drove_alone',
 'different_house_year_ago_different_city',
 'different_house_year_ago_same_city',
 'employed_agriculture_forestry_fishing_hunting_mining',
 'employed_arts_entertainment_recreation_accommodation_food',
 'employed_construction',
 'employed_education_health_social',
 'employed_finance_insurance_real_estate',
 'employed_information',
 'employed_manufacturing',
 'employed_other_services_not_public_admin',
 'employed_public_administration',
 'employed_retail_trade',
 'employed_science_management_admin_waste',
 'employed_transportation_warehousing_utilities',
 'employed_wholesale_trade',
 'female_female_households',
 'four_more_cars',
 'gini_index',
 'graduate_professional_degree',
 'group_quarters',
 'high_school_including_ged',
 'households_public_asst_or_food_stamps',
 'in_grades_1_to_4',
 'in_grades_5_to_8',
 'in_grades_9_to_12',
 'in_school',
 'in_undergrad_college',
 'less_than_high_school_graduate',
 'male_45_64_associates_degree',
 'male_45_64_bachelors_degree',
 'male_45_64_graduate_degree',
 'male_45_64_less_than_9_grade',
 'male_45_64_grade_9_12',
 'male_45_64_high_school',
 'male_45_64_some_college',
 'male_45_to_64',
 'male_male_households',
 'management_business_sci_arts_employed',
 'no_car',
 'no_cars',
 'not_us_citizen_pop',
 'occupation_management_arts',
 'occupation_natural_resources_construction_maintenance',
 'occupation_production_transportation_material',
 'occupation_sales_office',
 'occupation_services',
 'one_car',
 'two_cars',
 'three_cars',
 'pop_25_64',
 'pop_determined_poverty_status',
 'population_1_year_and_over',
 'population_3_years_over',
 'poverty',
 'sales_office_employed',
 'some_college_and_associates_degree',
 'walked_to_work',
 'worked_at_home',
 'workers_16_and_over',
 'commute_35_44_mins',
 'commute_60_more_mins',
 'commute_less_10_mins',
 'commuters_16_over',
 'hispanic_any_race',
 'year_usable']

In [13]:
df2 = pd.DataFrame()
df2['zip'] = df['zip']
df2['census_period'] = df['do_date']
df2['year_usable'] = df['year_usable']

In [14]:
pre_working_cols = [
    'male_under_5',
    'male_5_to_9',
    'male_10_to_14',
    'male_15_to_17',
    'female_under_5',
    'female_5_to_9',
    'female_10_to_14',
    'female_15_to_17'
]

adult_cols = [
    'male_18_to_19',
    'male_20',
    'male_21',
    'male_22_to_24',
    'male_25_to_29',
    'male_30_to_34',
    'male_35_to_39',
    'female_18_to_19',
    'female_20',
    'female_21',
    'female_22_to_24',
    'female_25_to_29',
    'female_30_to_34',
    'female_35_to_39'
]

older_adult_cols = [
    'female_40_to_44',
    'female_45_to_49',
    'female_50_to_54',
    'female_55_to_59',
    'female_60_to_61',
    'female_62_to_64',
    'male_40_to_44',
    'male_45_to_49',
    'male_50_to_54',
    'male_55_to_59',
    'male_60_61',
    'male_62_64'
]

senior_cols = [
    'female_65_to_66',
    'female_67_to_69',
    'female_70_to_74',
    'female_75_to_79',
    'female_80_to_84',
    'female_85_and_over',
    'male_65_to_66',
    'male_67_to_69',
    'male_70_to_74',
    'male_75_to_79',
    'male_80_to_84',
    'male_85_and_over'
]

df2['percent_white'] = df['white_pop']/df['total_pop']
df2['percent_black'] = df['black_pop']/df['total_pop']
df2['percent_asian'] = df['asian_pop']/df['total_pop']
df2['percent_hispanic'] = df['hispanic_pop']/df['total_pop']
df2['percent_native_am'] = df['amerindian_pop']/df['total_pop']
df2['percent_other_race'] = df['other_race_pop']/df['total_pop']

df2['percent_0_17'] = df[pre_working_cols].sum(axis=1)/df['total_pop']
df2['percent_18_39'] = df[adult_cols].sum(axis=1)/df['total_pop']
df2['percent_40_64'] = df[older_adult_cols].sum(axis=1)/df['total_pop']
df2['percent_65+'] = df[senior_cols].sum(axis=1)/df['total_pop']

# trying to measure demand of rental units
df2['percent_rental_units_vacant'] = df['vacant_housing_units_for_rent']/(df['vacant_housing_units_for_rent']+df['housing_units_renter_occupied'])
df2['percent_rental_units_occupied'] = df['housing_units_renter_occupied']/(df['vacant_housing_units_for_rent']+df['housing_units_renter_occupied'])

In [15]:
total_dwellings = df[[ 'dwellings_1_units_detached',
                                         'dwellings_1_units_attached',
                                         'dwellings_2_units',
                                         'dwellings_3_to_4_units',
                                         'dwellings_5_to_9_units',
                                         'dwellings_10_to_19_units',
                                         'dwellings_20_to_49_units',
                                         'dwellings_50_or_more_units']].sum(axis = 'columns')

In [16]:
df['derived_pop_over_25']= df[['male_25_to_29',
 'male_30_to_34',
 'male_35_to_39',
 'male_40_to_44',
 'male_45_to_49',
 'male_50_to_54',
 'male_55_to_59',
 'male_60_61',
 'male_62_64',
 'male_65_to_66',
 'male_67_to_69',
 'male_70_to_74',
 'male_75_to_79',
 'male_80_to_84',
 'male_85_and_over',
 'female_25_to_29',
 'female_30_to_34',
 'female_35_to_39',
 'female_40_to_44',
 'female_45_to_49',
 'female_50_to_54',
 'female_55_to_59',
 'female_60_to_61',
 'female_62_to_64',
 'female_65_to_66',
 'female_67_to_69',
 'female_70_to_74',
 'female_75_to_79',
 'female_80_to_84',
 'female_85_and_over']].sum(axis='columns')

#EDUCATION
df2['percent_graduate_deg'] = df['graduate_professional_degree']/df['total_pop'] #population 
df2['percent_bachelors'] = df['bachelors_degree_2']/df['total_pop'] #population 
df2['percent_associates'] = df['some_college_and_associates_degree']/df['derived_pop_over_25'] #25 and over 
df2['percent_highschool'] = df['high_school_including_ged']/df['derived_pop_over_25']  #25 and over 
df2['percent_less_highschool'] = df['less_than_high_school_graduate']/df['derived_pop_over_25']  #25 and over

#COMMUTE
df2['percent_commute_public_transport'] = df['commuters_by_public_transportation']/df['commuters_16_over']

df2['percent_commute_less_30'] = (df[['commute_5_9_mins',
                                   'commute_10_14_mins',
                                   'commute_15_19_mins',
                                   'commute_20_24_mins',
                                   'commute_25_29_mins']].sum(axis='columns'))/df['commuters_16_over']

df2['percent_buildings_less_10_units'] = (df[['dwellings_1_units_detached',
                                         'dwellings_1_units_attached',
                                         'dwellings_2_units',
                                         'dwellings_3_to_4_units',
                                         'dwellings_5_to_9_units']].sum(axis='columns')) / total_dwellings

                                        
df2['percent_buildings_10_19_units'] = df['dwellings_10_to_19_units'] / total_dwellings
                                        

df2['percent_buildings_20_49_units'] = df['dwellings_20_to_49_units'] / total_dwellings
                                        

df2['percent_buildings_50+_units'] = df['dwellings_50_or_more_units'] / total_dwellings

df2['percent_commute_30_to_59'] = (df[['commute_30_34_mins',
                                     'commute_35_44_mins',
                                     'commute_35_39_mins',
                                     'commute_40_44_mins',
                                     'commute_45_59_mins']].sum(axis='columns'))/df['commuters_16_over']

df2['percent_commute_60_to_89'] = df['commute_60_89_mins']/df['commuters_16_over']

df2['percent_commute_90_more'] = df['commute_90_more_mins']/df['commuters_16_over']

# MOVERS
# moved to this city from another city 
df2['percent_new_city'] = df['different_house_year_ago_different_city']/df['total_pop']

# moved to a new unit in this same city
df2['percent_new_unit'] = df['different_house_year_ago_same_city']/df['total_pop']

# OWNER OCCUPIED
df2['percent_units_owner_occupied'] = df['owner_occupied_housing_units']/df['housing_units']

In [17]:
# features to keep/keep in slightly modified form

# change median year building built to median building age
df2['median_building_age'] = (df['year_usable']-2) - df['median_year_structure_built']
df2['income_per_capita'] = df['income_per_capita']
df2['poverty_rate'] = df['poverty']/df['pop_determined_poverty_status']
df2['total_pop'] = df['total_pop']
df2['percent_workforce_unemployed'] = df['unemployed_pop']/df['civilian_labor_force']
df2['percent_work_from_home'] = df['worked_at_home']/df['civilian_labor_force']
df2['median_age'] = df['median_age']
df2['percent_female'] = df['female_pop']/df['total_pop']
df2['gini_index'] = df['gini_index']
df2['percent_not_us_citizen'] = df['not_us_citizen_pop']/df['total_pop']

In [18]:
df2

,zip,census_period,year_usable,percent_white,percent_black,percent_asian,percent_hispanic,percent_native_am,percent_other_race,percent_0_17,...,median_building_age,income_per_capita,poverty_rate,total_pop,percent_workforce_unemployed,percent_work_from_home,median_age,percent_female,gini_index,percent_not_us_citizen
0,01013,20072011,2013,0.729579,0.020723,0.013756,0.218793,0.000000,0.005002,0.230494,...,62.0,20433.0,0.190522,22391,0.104113,0.008853,36.4,0.510250,0.4210,0.055960
1,01013,20082012,2014,0.714417,0.023463,0.013473,0.231235,0.000000,0.004491,0.224682,...,62.0,20940.0,0.201543,21822,0.104320,0.014770,36.6,0.501650,0.4179,0.057190
2,01013,20092013,2015,0.720119,0.027857,0.016777,0.217971,0.001357,0.005065,0.217248,...,66.0,20889.0,0.173591,22113,0.113411,0.012946,35.5,0.506851,0.4110,0.056483
3,01013,20102014,2016,0.713799,0.017445,0.016638,0.237499,0.000538,0.002197,0.221131,...,72.0,21371.0,0.155696,22299,0.115569,0.013701,35.8,0.512669,0.4061,0.050182
4,01013,20112015,2017,0.703894,0.022238,0.018442,0.241627,0.001116,0.001652,0.222336,...,73.0,21477.0,0.169816,22394,0.114075,0.020243,34.9,0.514200,0.4117,0.050013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92647,99901,20092013,2015,0.653872,0.002271,0.063146,0.044026,0.142407,0.002710,0.233756,...,38.0,31563.0,0.101846,13651,0.086316,0.021073,38.7,0.478353,0.3981,0.025493
92648,99901,20102014,2016,0.654374,0.004016,0.061487,0.046444,0.143932,0.000000,0.232584,...,38.0,31487.0,0.114447,13694,0.085095,0.022509,38.8,0.481233,0.4057,0.023952
92649,99901,20112015,2017,0.649705,0.004228,0.073631,0.048334,0.135379,0.001604,0.230079,...,40.0,32010.0,0.121194,13717,0.078951,0.023050,38.7,0.485602,0.4110,0.025953
92650,99901,20122016,2018,0.645762,0.004947,0.076319,0.046126,0.129138,0.005384,0.225609,...,40.0,32671.0,0.108124,13745,0.075428,0.026582,39.2,0.485922,0.4158,0.035504
92651,99901,20132017,2019,0.644756,0.005447,0.077426,0.047574,0.135096,0.004213,0.222836,...,41.0,33755.0,0.106987,13768,0.069999,0.024453,39.5,0.485401,0.4157,0.033338

In [20]:
df2.to_csv('./../data/acs_engineered_features.csv', index=False)