In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
guns = pd.read_csv('./../data/google_trend/google_terms_guns.csv')

In [3]:
jobs = pd.read_csv('./../data/google_trend/google_terms_jobs.csv')

In [4]:
lgbt = pd.read_csv('./../data/google_trend/google_terms_lgbt.csv')

In [5]:
social = pd.read_csv('./../data/google_trend/google_terms_social.csv')

In [6]:
travels = pd.read_csv('./../data/google_trend/google_terms_travels.csv')

In [7]:
woty = pd.read_csv('./../data/google_trend/google_terms_woty.csv')

In [8]:
disaster = pd.read_csv('./../data/google_trend/google_terms_disasters.csv')

In [9]:
gentrification = pd.read_csv('./../data/google_trend/google_terms_gentrification2.csv')

In [10]:
multifamily = pd.read_csv('./../data/google_trend/google_terms_multifamily_for_rent.csv')

In [11]:
homes = pd.read_csv('./../data/google_trend/google_terms_homes_for_rent.csv')

In [12]:
apartment = pd.read_csv('./../data/google_trend/google_terms_apartment_for_rent.csv')

In [13]:
df_list = [guns, jobs, lgbt, social, travels, woty, disaster, gentrification, multifamily, homes, apartment]
i=0
ss = StandardScaler()
for item in df_list:
    item.columns = item.columns.map(lambda x: x.lower())
    item.drop(columns = item.columns[8:], inplace=True)
    for col in item.columns[3:]:
        temp = pd.DataFrame(item[col])
        temp = ss.fit_transform(temp)
        item[col] = temp
    item.drop(columns = 'ispartial', inplace = True)
    if i != 0:
        item.drop(columns = ['metro', 'datetime'], inplace = True)
    i+=1

C:\Users\fayma\anaconda3\envs\env1\lib\site-packages\sklearn\utils\extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\fayma\anaconda3\envs\env1\lib\site-packages\sklearn\utils\extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)
C:\Users\fayma\anaconda3\envs\env1\lib\site-packages\sklearn\utils\extmath.py:847: RuntimeWarning: invalid value encountered in true_divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\fayma\anaconda3\envs\env1\lib\site-packages\sklearn\utils\extmath.py:689: RuntimeWarning: Degrees of freedom <= 0 for slice.
  result = op(x, *args, **kwargs)

In [14]:
full_trends = pd.concat(df_list, axis = 1).fillna(0)

In [16]:
full_trends_backup = full_trends.copy()

In [21]:
full_trends['starbucks2'] = full_trends['starbucks'].mean(axis=1)

In [25]:
full_trends.drop(columns = 'starbucks', inplace = True)

In [27]:
full_trends.rename(columns = {'starbucks2' : 'starbucks'}, inplace = True)

In [37]:
for col in full_trends.columns:
    print(col)
    print((full_trends[col]==0).value_counts())

metro
False    9855
Name: metro, dtype: int64
datetime
False    9855
Name: datetime, dtype: int64
gun range
False    9417
True      438
Name: gun range, dtype: int64
gun licence
True     9563
False     292
Name: gun licence, dtype: int64
gun control
False    9855
Name: gun control, dtype: int64
gun violence
False    9344
True      511
Name: gun violence, dtype: int64
job opportunities
False    8760
True     1095
Name: job opportunities, dtype: int64
unemployment
False    9855
Name: unemployment, dtype: int64
retirement
False    9855
Name: retirement, dtype: int64
layoff
False    9782
True       73
Name: layoff, dtype: int64
lgbt
False    9855
Name: lgbt, dtype: int64
same sex marriage
False    9052
True      803
Name: same sex marriage, dtype: int64
they
False    9855
Name: they, dtype: int64
pronouns
False    9782
True       73
Name: pronouns, dtype: int64
black lives matter
False    9855
Name: black lives matter, dtype: int64
political correctness
True     5767
False    4088
Name: political correctness, dtype: int64
make america great again
False    9709
True      146
Name: make america great again, dtype: int64
euthanasia
False    9636
True      219
Name: euthanasia, dtype: int64
getaway
False    9782
True       73
Name: getaway, dtype: int64
places to go
False    9782
True       73
Name: places to go, dtype: int64
tourists attraction
True    9855
Name: tourists attraction, dtype: int64
flight tickets
False    8468
True     1387
Name: flight tickets, dtype: int64
twitter
False    9855
Name: twitter, dtype: int64
hashtag
False    9709
True      146
Name: hashtag, dtype: int64
tender age shelter
True    9855
Name: tender age shelter, dtype: int64
fake news
False    9709
True      146
Name: fake news, dtype: int64
hurricane
False    9855
Name: hurricane, dtype: int64
wildfire
False    9052
True      803
Name: wildfire, dtype: int64
flood
False    9855
Name: flood, dtype: int64
fire
False    9855
Name: fire, dtype: int64
trader joe's
False    9563
True      292
Name: trader joe's, dtype: int64
whole foods
False    9782
True       73
Name: whole foods, dtype: int64
lululemon
False    9855
Name: lululemon, dtype: int64
thrift
False    9855
Name: thrift, dtype: int64
condos for rent
False    8322
True     1533
Name: condos for rent, dtype: int64
duplex apartments for rent
True     8103
False    1752
Name: duplex apartments for rent, dtype: int64
townhomes for rent
False    7957
True     1898
Name: townhomes for rent, dtype: int64
townhouses for rent
False    6278
True     3577
Name: townhouses for rent, dtype: int64
home for rent
False    9344
True      511
Name: home for rent, dtype: int64
house for rent
False    9782
True       73
Name: house for rent, dtype: int64
townhome for rent
True     8030
False    1825
Name: townhome for rent, dtype: int64
townhouse for rent
True     5475
False    4380
Name: townhouse for rent, dtype: int64
apartment for rent
False    9636
True      219
Name: apartment for rent, dtype: int64
studio for rent
False    7081
True     2774
Name: studio for rent, dtype: int64
1 bedroom for rent
False    6789
True     3066
Name: 1 bedroom for rent, dtype: int64
3 bedroom for rent
False    7957
True     1898
Name: 3 bedroom for rent, dtype: int64
starbucks
False    9855
Name: starbucks, dtype: int64

In [33]:
full_trends

,metro,datetime,gun range,gun licence,gun control,gun violence,job opportunities,unemployment,retirement,layoff,...,townhouses for rent,home for rent,house for rent,townhome for rent,townhouse for rent,apartment for rent,studio for rent,1 bedroom for rent,3 bedroom for rent,starbucks
0,Springfield,2014-01-01,-1.569568,0.0,-0.986047,-0.723220,0.096863,3.466751,-1.425905,-0.823717,...,0.0,-0.629886,-0.622713,0.0,0.0,-1.390248,-1.181638,-0.872013,-1.100628,-1.712329
1,Springfield,2014-02-01,0.795072,0.0,0.879861,0.254251,1.061035,1.934232,-1.217118,-0.823717,...,0.0,-1.612318,-0.622713,0.0,0.0,-0.050671,0.701568,0.097872,-1.100628,-1.241616
2,Springfield,2014-03-01,0.795072,0.0,0.879861,-0.723220,-0.385223,0.991144,0.348785,-0.823717,...,0.0,0.025069,0.565707,0.0,0.0,-0.172450,-0.475436,-0.872013,-1.100628,-1.268533
3,Springfield,2014-04-01,0.795072,0.0,-0.239684,-0.723220,-1.349394,1.462688,-0.799544,-0.823717,...,0.0,-1.612318,-0.622713,0.0,0.0,0.314669,-1.181638,-0.872013,-1.100628,-0.743268
4,Springfield,2014-05-01,-0.150784,0.0,0.133498,0.742986,0.578949,1.875289,0.661965,-0.823717,...,0.0,-0.629886,-0.771265,0.0,0.0,-1.755587,-1.181638,-0.872013,-0.049096,-0.248671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9850,Anchorage,2019-09-01,-1.569568,0.0,0.337051,0.742986,0.000000,0.391463,-1.488541,-0.823717,...,0.0,-1.612318,-0.229486,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,1.592431
9851,Anchorage,2019-10-01,-0.434541,0.0,-0.324498,-0.723220,0.000000,0.989435,1.016903,-0.823717,...,0.0,-1.612318,0.277340,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,0.124153
9852,Anchorage,2019-11-01,0.322144,0.0,0.116535,-0.723220,0.000000,0.562312,-0.903937,-0.823717,...,0.0,-1.612318,-1.749964,0.0,0.0,0.517635,0.000000,0.000000,0.000000,1.697509
9853,Anchorage,2019-12-01,-0.434541,0.0,-0.986047,-0.723220,0.000000,1.416559,0.098240,-0.823717,...,0.0,-1.612318,1.797818,0.0,0.0,-0.131857,0.000000,0.000000,0.000000,0.847381
9854,Anchorage,2020-01-01,-1.569568,0.0,-0.986047,-0.723220,0.000000,2.356230,0.432300,-0.823717,...,0.0,-0.302408,-0.989725,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,-0.243241

In [38]:
full_trends.drop(columns = ['tender age shelter', 'tourists attraction', 'gun licence'], inplace = True)

In [39]:
full_trends.rename(columns = {'metro':'Metro'}, inplace = True)

In [40]:
# full_trends.to_csv('./../data/google_trends_full.csv', index = False)

In [41]:
df = pd.read_csv('./../data/zri_acs_bikeshare_merged.csv', index_col = 0)

In [42]:
df

,City,State,Metro,CountyName,zri,year,month,datetime,percent_white,percent_black,...,total_pop,percent_workforce_unemployed,percent_work_from_home,median_age,percent_female,gini_index,percent_not_us_citizen,bs_total_stations,bs_total_systems,has_bike_sharing
zip,,,,,,,,,,,,,,,,,,,,,
1013,Chicopee,MA,Springfield,Hampden County,928.0,2014,1,2014-01-01,0.728315,0.020951,...,22343.583333,0.104130,0.009346,36.416667,0.509533,0.420742,0.056062,0.0,0.0,0
1013,Chicopee,MA,Springfield,Hampden County,931.0,2014,2,2014-02-01,0.727052,0.021179,...,22296.166667,0.104147,0.009839,36.433333,0.508816,0.420483,0.056165,0.0,0.0,0
1013,Chicopee,MA,Springfield,Hampden County,934.0,2014,3,2014-03-01,0.725788,0.021408,...,22248.750000,0.104165,0.010332,36.450000,0.508100,0.420225,0.056267,0.0,0.0,0
1013,Chicopee,MA,Springfield,Hampden County,929.0,2014,4,2014-04-01,0.724525,0.021636,...,22201.333333,0.104182,0.010825,36.466667,0.507383,0.419967,0.056370,0.0,0.0,0
1013,Chicopee,MA,Springfield,Hampden County,929.0,2014,5,2014-05-01,0.723261,0.021864,...,22153.916667,0.104199,0.011318,36.483333,0.506666,0.419708,0.056472,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1277.0,2019,8,2019-08-01,0.796036,0.008872,...,60057.000000,0.102326,0.049199,33.566667,0.475244,0.399400,0.018076,0.0,0.0,0
99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1271.0,2019,9,2019-09-01,0.795709,0.008765,...,60203.000000,0.102254,0.049419,33.575000,0.475511,0.399650,0.018306,0.0,0.0,0
99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1299.0,2019,10,2019-10-01,0.795381,0.008658,...,60349.000000,0.102181,0.049640,33.583333,0.475778,0.399900,0.018537,0.0,0.0,0
99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1261.5,2019,11,2019-11-01,0.795054,0.008550,...,60495.000000,0.102109,0.049861,33.591667,0.476045,0.400150,0.018767,0.0,0.0,0
99654,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1224.0,2019,12,2019-12-01,0.794726,0.008443,...,60641.000000,0.102037,0.050081,33.600000,0.476311,0.400400,0.018997,0.0,0.0,0

In [43]:
pd.merge(df, full_trends, how = 'left', on = ['Metro', 'datetime'])

,City,State,Metro,CountyName,zri,year,month,datetime,percent_white,percent_black,...,townhouses for rent,home for rent,house for rent,townhome for rent,townhouse for rent,apartment for rent,studio for rent,1 bedroom for rent,3 bedroom for rent,starbucks
0,Chicopee,MA,Springfield,Hampden County,928.0,2014,1,2014-01-01,0.728315,0.020951,...,0.0,-0.629886,-0.622713,0.0,0.0,-1.390248,-1.181638,-0.872013,-1.100628,-1.712329
1,Chicopee,MA,Springfield,Hampden County,931.0,2014,2,2014-02-01,0.727052,0.021179,...,0.0,-1.612318,-0.622713,0.0,0.0,-0.050671,0.701568,0.097872,-1.100628,-1.241616
2,Chicopee,MA,Springfield,Hampden County,934.0,2014,3,2014-03-01,0.725788,0.021408,...,0.0,0.025069,0.565707,0.0,0.0,-0.172450,-0.475436,-0.872013,-1.100628,-1.268533
3,Chicopee,MA,Springfield,Hampden County,929.0,2014,4,2014-04-01,0.724525,0.021636,...,0.0,-1.612318,-0.622713,0.0,0.0,0.314669,-1.181638,-0.872013,-1.100628,-0.743268
4,Chicopee,MA,Springfield,Hampden County,929.0,2014,5,2014-05-01,0.723261,0.021864,...,0.0,-0.629886,-0.771265,0.0,0.0,-1.755587,-1.181638,-0.872013,-0.049096,-0.248671
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93667,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1277.0,2019,8,2019-08-01,0.796036,0.008872,...,0.0,0.570864,-0.989725,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,1.022937
93668,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1271.0,2019,9,2019-09-01,0.795709,0.008765,...,0.0,-1.612318,-0.229486,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,1.592431
93669,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1299.0,2019,10,2019-10-01,0.795381,0.008658,...,0.0,-1.612318,0.277340,0.0,0.0,-1.755587,0.000000,0.000000,0.000000,0.124153
93670,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1261.5,2019,11,2019-11-01,0.795054,0.008550,...,0.0,-1.612318,-1.749964,0.0,0.0,0.517635,0.000000,0.000000,0.000000,1.697509
93671,Wasilla,AK,Anchorage,Matanuska Susitna Borough,1224.0,2019,12,2019-12-01,0.794726,0.008443,...,0.0,-1.612318,1.797818,0.0,0.0,-0.131857,0.000000,0.000000,0.000000,0.847381